### ISSUE TITLE
Eagle Library

### ISSUE THREAD

**Issue by 32teeth** [adafruit/Adafruit-CP2104-Friend-PCB#1]
Looking for microbuilder.lbr

```
device: CP2104 
footprint: QFN24_4MM_SMSC
library: microbuilder
```
<img width="580" alt="Screen Shot 2019-04-25 at 4 04 08 PM" src="https://user-images.githubusercontent.com/75797/56765014-16ecdd80-6774-11e9-9264-77120fb793ad.png">

**Comment by ladyada** [comment]
its not public, you can extract library items or copy and paste them to your schematic
